spring:
  h2:
    console:
      enabled: true
  profiles:
    active: jpadao
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl